version: '3'
services:
  web:
    image: 9876543210.dkr.ecr.eu-west-1.amazonaws.com/kazed-repository
    ports:
      - "8080:8080"
    logging:
      driver: awslogs
      options:
        awslogs-group: stockport-api
        awslogs-region: eu-west-1
        awslogs-stream-prefix: web
