version: 1
task_definition:
  task_execution_role: ecsTaskExecutionRole
  ecs_network_mode: awsvpc
  task_size:
    mem_limit: 0.5GB
    cpu_limit: 256
run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - "subnet-01231231231223123"
        - "subnet-02342342342342344"
      security_groups:
        - "sg-01231231231231233"
      assign_public_ip: ENABLED
